[build]
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
